### ISSUE TITLE
autopair-newline and ada-mode conflict

### ISSUE THREAD

**Issue by corentincam** [capitaomorte/autopair#53]
Under ada-mode, when using the command `autopair-newline` (binded to RET), emacs raises a "Variable binding depth exceeds max-specpdl-size" error.

**Comment by joaotavora** [comment]
@CorentinCAM. I can't reproduce from this from the information you've given me. There's probably something else in your configuration. Can you reproduce this from a clean `emacs -Q` run?

**Anyway** I *very very* strongly recommend that you replace `autopair` by something which is in emacs since version 24.4 (if I'm not mistaken), which is `M-x electric-pair-mode`. You see, I designed that to replace `autopair` it does everything `autopair` does and better. And, almost surely, it doesn't  have this problem.

I'm closing, but if you don't agree I can reopen.

**Comment by corentincam** [comment]
Thanks for the answer, `electric-pair-mode` works indeed.
